version: "3"

services:

  php-fpm:
    container_name: tetrinet_phpfpm
    build:
      context: ./php-fpm
    volumes:
      - ./../../:/var/www/public/
    environment:
      XDEBUG_CONFIG: "remote_host=172.25.0.1 client_host=172.25.0.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      # - redis
      - db

  nginx:
    container_name: tetrinet_nginx
    build:
      context: ./nginx
    volumes:
      - ./../../:/var/www/public/
    ports:
      - 8080:80
    depends_on:
      - php-fpm

#  redis:
#    image: redis
#    command: ["sh", "-c", "exec redis-server"]

  db:
    container_name: tetrinet_mysql
    build:
      context: ./mysql
    command: '--sql_mode="" --default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'tetrinet'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
