export {StoreGameDataInStorage} from "./StoreGameDataInStorage"
export {ClearGameDataInStorage} from "./ClearGameDataInStorage"
export {LoadGameDataFromStorage} from "./LoadGameDataFromStorage"
export {LoadPlayerName} from "./LoadPlayerName"
export {StorePlayerName} from "./StorePlayerName"